// <auto-generated />
namespace proje1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class removesalon_kategori : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removesalon_kategori));
        
        string IMigrationMetadata.Id
        {
            get { return "202412202127030_removesalon_kategori"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
